import os
print("*" * 80)
os.system("sudo apt update")
os.system("sudo apt -y upgrade")
os.system("python3 -V")
os.system("sudo apt install -y python3-pip")
print("*" * 80)
os.system("pip install numpy")
print("*" * 80)
os.system("pip install python-binance")
print("*" * 80)
os.system("pip install backtrader")
print("*" * 80)
os.system("pip install pandas")
print("*" * 80)
os.system("pip install prettytable")
print("*" * 80)
os.system("pip install openpyxl")

os.system("chmod +x erun.sh")
os.system("chmod +x estop.sh")

# os.system("pip install backtrader-binance")
# print("*" * 80)
# os.system("pip install tensorflow")
# print("*" * 80)
# os.system("pip install tqdm")
# print("*" * 80)
# os.system("pip install -U scikit-learn")
# print("*" * 80)
# os.system("pip install scipy")
# print("*" * 80)
# os.system("pip install psutil")
# print("*" * 80)
